name: Build Website

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [plotnine-release, push-plotnine-examples-main]
  workflow_dispatch:

jobs:
  build-site:
    name: Build site for plotnine.org
    uses: ./.github/workflows/build.yml
    with:
      plotnine-branch: release
      target-folder: "."
